module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    // extend: {
    //   backgroundImage: {
    //     "live-chat-bg": "url('/assets/live-chat-bg.svg')",
    //   },
    // },
    colors: {
      bgMain: "#fff",
      orange: "#FF5C0A",
      blue: "#0C8EFF",
      violet: "#504EE4",
      highlight: "#0591FC",
      textMain: "#0D144A",
      white: "#fff",
    },
    fontFamily: {
      poppins: ['"Poppins"', "sans-serif"],
      paytone: ["Paytone", "sans-serif"],
    },
    fontSize: {
      sm: "14px",
      "1xl": "1rem",
      "1.3xl": "1.3rem",
      "2xl": "2rem",
      "3xl": "3rem",
      "4xl": "4rem",
      "5xl": "5rem",
      "6xl": "6rem",
      "7xl": "7rem",
      "8xl": "8rem",
      "9xl": "9rem",
      "10xl": "10rem",
    },
    maxWidth: {
      "mw-0": "none",
      "mw-1/3": "33.333333%",
      "mw-2/3": "66.666667%",
      "mw-1/4": "25%",
      "mw-2/4": "50%",
      "mw-3/4": "75%",
      "mw-1/5": "20%",
      "mw-2/5": "40%",
      "mw-3/5": "60%",
      "mw-4/5": "80%",
      "mw-90": "90%",
    },
    lineHeight: {
      "1rem": "1rem",
      "2rem": "2rem",
      "3rem": "3rem",
      "4rem": "4rem",
      "5rem": "5rem",
      "6rem": "6rem",
      "7rem": "7rem",
      "8rem": "8rem",
      "9rem": "9rem",
      "10rem": "10rem",
    },
  },
  plugins: [],
};
